const Categories = [
    {
      id: 1,
      name: "WINTER COLLECTION",
      subcategories: [
        "Rugby Shirts",
        "Sweatshirts",
        "Sweat Pants",
        "Sweaters",
        "Zippers",
        "Mens shawls",
        "Jackets",
        "Wool Jacket",
        "Long Coats",
        "Shackets & Shirts",
        "Hoodies",
        "Thermal Suits",
        "Pakol caps",
        "Winter Looks",
        "Co-Ord Sets",
      ],
    },
    {
      id: 2,
      name: "SHIRTS",
      subcategories: [
        "Business Casual",
        "Half Sleeve Shirts",
        "The White Club",
        "Formal Shirts",
        "Plain Shirts",
        "Check Shirts",
        "Stripe Shirts",
        "Be Bright",
        "Printed Shirts",
        "Double Cuff",
        "Textured Shirts",
        "Designer Shirts",
        "Knit Formal Shirts",
        "White Collar Club",
        "Casual Shirts",
      ],
    },
    {
      id: 3,
      name: "TROUSERS",
      subcategories: [
        "Formal Trousers",
        "Cotton Trousers",
        "Denim Jeans",
        "600 Traveler",
        "700 Smart Fit",
        "800 Straight Fit",
        "Casual Pant",
      ],
    },
    {
      id: 4,
      name: "SUITING",
      subcategories: [
        "Suit",
        "Lapel Pin",
        "Coat Button",
        "Safari Suit",
        "Coat",
        "Wedding Edits",
        "Western Waistcoat",
        "Tie & Cufflink Set",
        "Gift Box",
        "Pocket Square",
        "Bow Tie",
        "Tie Pin",
      ],
    },
    {
      id: 5,
      name: "ETHNIC WEAR",
      subcategories: [
        "Kameez Shalwar",
        "Kurta Pajama",
        "Ethnic Combo",
        "Kurtas",
        "Shalwar",
        "Ethnic Pajama",
        "Waistcoats",
        "Designer Waist Coat",
        "Saleem Sheikh",
        "SS Shalwar Suit",
        "SS WAISTCOATS",
        "SS KURTAS",
      ],
    },
    {
      id: 6,
      name: "ACTIVE WEAR",
      subcategories: [
        "Gym Short",
        "Gym Tee",
        "Gym Trouser",
        "Track Suit",
        "Tank Top",
      ],
    },
    {
      id: 7,
      name: "CASUAL PAJAMA",
      subcategories: ["nill"],
    },
    {
      id: 8,
      name: "LOUNGEWEAR",
      subcategories: ["T-Shirt & Pajama"],
    },
    {
      id: 9,
      name: "ACCESSORIES",
      subcategories: [
        "Ties",
        "Cufflinks",
        "Belt",
        "Wallets",
        "Fragrance",
        "Socks",
        "Suspender",
        "Undergarments",
        "Boxer Shorts",
        "Vest",
      ],
    },
    {
      id: 10,
      name: "SUMMER COLLECTION",
      subcategories: [
        "All Polos",
        "Premium Polos",
        "T Shirts",
        "Premium Tee",
        "Graphic Tees",
        "Crew Neck",
        "Resort Shirts",
        "Basic Tees",
        "Men Shorts",
        "Mens Chinos",
        "Linen Shirt",
      ],
    },
    {
      id: 11,
      name: "SALE",
      subcategories: ["nill"],
    },
  ];
  
  export default Categories;
  